site_name:        VarianceComponentModels.jl
repo_url:         https://github.com/OpenMendel/VarianceComponentModels.jl
site_description: Utilities for fitting and testing variance component models
site_author:      Hua Zhou

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - MLE/REML: man/mle_reml.md
  - Heritability: man/heritability.md
- API: man/api.md
